apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "tasksdb"
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        # AJOUT : Montage du script d'initialisation
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      # AJOUT : Référence au ConfigMap créé précédemment
      - name: init-script
        configMap:
          name: postgres-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: 5432